// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApGLOTr6TRZSQxixbd9iydAIbA6t-GpJI',
    appId: '1:1071160425340:web:05b8ef6548d3c8f4f1c2f9',
    messagingSenderId: '1071160425340',
    projectId: 'cmsc23-fmcanedo',
    authDomain: 'cmsc23-fmcanedo.firebaseapp.com',
    storageBucket: 'cmsc23-fmcanedo.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAIvOF_i7in0FxEhkfjIUFl1EJfnWAmhFM',
    appId: '1:1071160425340:android:0591c0a454476323f1c2f9',
    messagingSenderId: '1071160425340',
    projectId: 'cmsc23-fmcanedo',
    storageBucket: 'cmsc23-fmcanedo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHU3Bdm1wbX7x9OXJDahfn10dCBvG1gHQ',
    appId: '1:1071160425340:ios:1ab59ff4cf599fb8f1c2f9',
    messagingSenderId: '1071160425340',
    projectId: 'cmsc23-fmcanedo',
    storageBucket: 'cmsc23-fmcanedo.appspot.com',
    iosClientId: '1071160425340-t1f44jqmv76voes9ghn11q68kuvsqopm.apps.googleusercontent.com',
    iosBundleId: 'com.example.week7NetworkingDiscussion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHU3Bdm1wbX7x9OXJDahfn10dCBvG1gHQ',
    appId: '1:1071160425340:ios:1ab59ff4cf599fb8f1c2f9',
    messagingSenderId: '1071160425340',
    projectId: 'cmsc23-fmcanedo',
    storageBucket: 'cmsc23-fmcanedo.appspot.com',
    iosClientId: '1071160425340-t1f44jqmv76voes9ghn11q68kuvsqopm.apps.googleusercontent.com',
    iosBundleId: 'com.example.week7NetworkingDiscussion',
  );
}
